ALTER TABLE country
    ADD CONSTRAINT COUNTRY_UNIQUE_ENGLISH_NAME UNIQUE (ENGLISH_NAME);

ALTER TABLE country_language
    ADD CONSTRAINT COUNTRY_LANGUAGE_UNIQUE_ENGLISH_NAME UNIQUE (ID_COUNTRY, ENGLISH_NAME);